### ISSUE TITLE
关于windows版本的一些建议

### ISSUE THREAD

**Issue by puyujian** [wanghongenpin/proxypin#119]
占用非常高，基本上我开一个晚上就内存可以到15G往上，吃不消呀。
1.建议抓的数据可以设置个自动清空，因为有些项目需要一直开启注入。
2.可以最小化到右下角
3.域名过滤有点问题，我的建议是可以只改相关域名的代理 但是目前好像会把其他的屏蔽掉

**Comment by M17764017422** [comment]
还有一个问题，Windows版只能按域名分组不方便，希望能按时间显示全部请求。也可以按状态码分组，提供多种分组查看方式

**Comment by SeaRat** [comment]
占用15G，这不会是内存泄露了吧

**Comment by wanghongenpin** [comment]
V1.1.5版本已经处理， 设置中增加内存清理，自动清理请求
https://github.com/wanghongenpin/network_proxy_flutter/releases/tag/V1.1.5
