### ISSUE TITLE
希望可以出一个两台设备互相扫码后的使用教程

### ISSUE THREAD

**Issue by Damonny** [wanghongenpin/proxypin#175]
希望可以出一个两台设备互相扫码后的使用教程，目前android无法root，同一局域网内android扫PC上的二维码，readme文档上说的流量转发不是太懂，是可以在pc上抓无root的手机上的数据包吗？

**Comment by wanghongenpin** [comment]
https://github.com/wanghongenpin/network_proxy_flutter/discussions/86

**Comment by wanghongenpin** [comment]
还是得root，相比于charles传统抓包，少了配置Wi-Fi代理步骤，并且可以抓到flutter应用流量（配置Wi-Fi抓不到）
