### ISSUE TITLE
手机端无法扫描连接Windows端的二维码

### ISSUE THREAD

**Issue by bobo680** [wanghongenpin/proxypin#216]
笔记本的所有防火墙已关闭，手机连的笔记本wifi热点,下载的也是最新的1.0.9版本，一扫windows的二维码就报：“连接失败，请检查是否在同一局域网和防火墙是否允许”
![1716304640178](https://github.com/wanghongenpin/network_proxy_flutter/assets/105871099/6aef0799-6332-4e8e-a1f3-7a12e6410e91)
![Uploading 图片.png…]()

**Comment by leichengbo** [comment]
![Uploading 微信截图_20240521232838.png…]()

**Comment by leichengbo** [comment]
![微信截图_20240521232838](https://github.com/wanghongenpin/network_proxy_flutter/assets/105871099/ca10b539-5b29-4dff-a925-7e5f37db2d66)

**Comment by wanghongenpin** [comment]
IOS本地网路一定得打开，然后桌面端抓包保持开启，也可以尝试手机浏览器 直接访问电脑ip:抓包端口 看网络能通不

![IMG_1068](https://github.com/wanghongenpin/network_proxy_flutter/assets/24794200/f65b5461-fe48-41d2-982c-7168924918ca)

**Comment by bmjoker** [comment]
android扫描windows二维码一直显示连接失败，请检查是否在同一局域网...有成功的吗

**Comment by SaKongA** [comment]
一样

**Comment by wanghongenpin** [comment]
> 这个功能有没有解释一下怎么用呀,配置是没问题的.设置->代理->端口设置后发现没有生效,我用ping软件测试设置的端口并没有打开

抓包得开启才会监听端口

**Comment by wanghongenpin** [comment]
必须保证同一个局域网，ios打开本地网络，电脑端开启抓包，windows有防火墙要允许访问，如果不行尝试用手机浏览器访问电脑ip+端口号能访问不
