### ISSUE TITLE
建议在工具箱添加一个正则表达式工具，方便使用

### ISSUE THREAD

**Issue by es3344520** [wanghongenpin/proxypin#264]
如题，修改响应或请求的时候，用正则表达式匹配效率高。 

 有时候需要测试一下写的正则表达式能不能用，这个时候要打开网页找类似的工具，虽然很好找，但稍晚麻烦一些。  
 
把这个正则表达式添加到工具箱，方便使用，提高效率。

**Comment by wanghongenpin** [comment]
V1.1.5版本已经处理
https://github.com/wanghongenpin/network_proxy_flutter/releases/tag/V1.1.5
