### ISSUE TITLE
安卓10编辑脚本时被系统识别为密码输入

### ISSUE THREAD

**Issue by mdikjse** [wanghongenpin/proxypin#296]
**描述错误(Describe the bug)**
荣耀30，安卓10系统编辑脚本时，编辑框被系统识别为输入密码，自动进入密码键盘了
**To Reproduce**
重现行为的步骤: 如具体应用抓包失败，请说明软件名称以及具体操作页面
进入软件后，点击左上角菜单->脚本->添加->然后点击脚本编辑框
**屏幕截图(Screenshots)*
![Screenshot_20240827_193540_com network proxy](https://github.com/user-attachments/assets/d588c44d-7449-4ee0-9e77-e5455c8ac27b)

**Comment by wanghongenpin** [comment]
遥遥领先, 写代码英文+数字够了

**Comment by wanghongenpin** [comment]
把输入法安全键盘关闭就好了, 更多信息见 https://github.com/flutter/flutter/issues/68571

![image](https://github.com/user-attachments/assets/0e441d5b-1076-4091-bbb6-c43fbd0a4952)

**Comment by mdikjse** [comment]
> 把输入法安全键盘关闭就好了, 更多信息见 [flutter/flutter#68571](https://github.com/flutter/flutter/issues/68571)
> 
> ![image](https://private-user-images.githubusercontent.com/24794200/362790351-0e441d5b-1076-4091-bbb6-c43fbd0a4952.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5NDk3NjcsIm5iZiI6MTcyNDk0OTQ2NywicGF0aCI6Ii8yNDc5NDIwMC8zNjI3OTAzNTEtMGU0NDFkNWItMTA3Ni00MDkxLWJiYjYtYzQzZmJkMGE0OTUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDE2Mzc0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViNDljYTVlM2U5YWM3OTIxNjFmNDFiN2U2YzcxZDg0YTkxZTQ1MDhhNzIwOGYzMWUwMTE0NWMzYzY5ZTEyZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IB8xJNRecuTKqFnLVEjPedVjA-vadwrR8poPRP5SLX8)

这个我知道，但是你关闭安全键盘后就会发现。。。。
![Screenshot_20240830_003915](https://github.com/user-attachments/assets/1edcb908-f333-4568-ab0c-2e3070b1421d)
，希望能在后续版本改善

**Comment by mdikjse** [comment]
是不是obscureText和keyboardType设置的问题

**Comment by mdikjse** [comment]
> 已找到问题，下个版本修复

太棒了，等你好消息！！！
