### ISSUE TITLE
脚本功能如何进行简单的md5加密？

### ISSUE THREAD

**Issue by God-Myw** [wanghongenpin/proxypin#307]
**您的功能请求是否与问题有关？请描述.**
对问题所在的清晰简洁的描述[...]

**描述您想要的解决方案**
对你想要发生的事情进行清晰简洁的描述.

**附加上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by wanghongenpin** [comment]
目前需要自己写js md5

**Comment by wanghongenpin** [comment]
V1.1.5版本已经处理
https://github.com/wanghongenpin/network_proxy_flutter/releases/tag/V1.1.5
文档：https://github.com/wanghongenpin/network_proxy_flutter/wiki/%E8%AF%B7%E6%B1%82%E9%87%8D%E5%86%99
