### ISSUE TITLE
脚本功能添加将数据保存到本地的接口

### ISSUE THREAD

**Issue by Sharl210** [wanghongenpin/proxypin#315]
使用场景：对应用特定url获取到响应数据后可以直接存在本地，比如抓包应用的视频链接的网址，就能将所有抓到的网址存在一个txt之后导入下载器批量下载，或者说直接响应就该是mp4也能直接存入本地

目前只能用日志作为下位替代，而且日志无法保存，上述直接写入文件无法实现的话希望将日志可选保存到本地也便于之后的分析或者是使用

**Comment by devcxm** [comment]
看了源码，扩展js功能会有点麻烦。

不过你可以尝试把抓取的包导出har，然后用python之类的脚本解析har提取你所需要的数据。

**Comment by Sharl210** [comment]
> 看了源码，扩展js功能会有点麻烦。
> 
> 不过你可以尝试把抓取的包导出har，然后用python之类的脚本解析har提取你所需要的数据。

那不如把日志默认开启（现在得手动去开才能收到日志，且加个开关是否保存至文件

**Comment by devcxm** [comment]
> > 看了源码，扩展js功能会有点麻烦。
> > 不过你可以尝试把抓取的包导出har，然后用python之类的脚本解析har提取你所需要的数据。
> 
> 那不如把日志默认开启（现在得手动去开才能收到日志，且加个开关是否保存至文件

我说的是在现有功能下可以通过这种方式自己实现，你想要什么数据都可以。加日志还要查看/管理/分享日志文件，需要花一定时间开发。

**Comment by Sharl210** [comment]
> > > 看了源码，扩展js功能会有点麻烦。
> > > 不过你可以尝试把抓取的包导出har，然后用python之类的脚本解析har提取你所需要的数据。
> > 
> > 那不如把日志默认开启（现在得手动去开才能收到日志，且加个开关是否保存至文件
> 
> 我说的是在现有功能下可以通过这种方式自己实现，你想要什么数据都可以。加日志还要查看/管理/分享日志文件，需要花一定时间开发。

OK了，暂时用另一个方案代替了,本地termux运行一个http服务，功能是将接受到的数据及文件名保存到本地相应文件，再用脚本功能转发数据到这个服务，有点繁琐但还是算好的了，完全解析har对我目前的需求有点代价过高时间成本也超了，而且不是实时的得后期处理实在划不来，这样算是伪保存日志了

**Comment by devcxm** [comment]
你这种方案更优，导出HAR不能实时，而且操作繁琐。但是解析HAR文件并不麻烦，就是一json读取几个key而已，花不了多久时间。

**Comment by Sharl210** [comment]
> 你这种方案更优，导出HAR不能实时，而且操作繁琐。但是解析HAR文件并不麻烦，就是一json读取几个key而已，花不了多久时间。

是这样，但是我试着导了一个har，发现文件还是蛮大的，包括APP启动时间我才抓了20秒，他就已经8 MB了，对于我只需要链接的话，属实有点绷不住，我如果要批量抓链接的话，占的内存有点大，总觉得很不舒服，以后如果需求比较复杂，再考虑吧，目前来看，我觉得这方法已经够用了

**Comment by devcxm** [comment]
接口数据不应该这么大，是不是有视频图片那些

> > 你这种方案更优，导出HAR不能实时，而且操作繁琐。但是解析HAR文件并不麻烦，就是一json读取几个key而已，花不了多久时间。
> 
> 是这样，但是我试着导了一个har，发现文件还是蛮大的，包括APP启动时间我才抓了20秒，他就已经8 MB了，对于我只需要链接的话，属实有点绷不住，我如果要批量抓链接的话，占的内存有点大，总觉得很不舒服，以后如果需求比较复杂，再考虑吧，目前来看，我觉得这方法已经够用了

**Comment by Sharl210** [comment]
> 接口数据不应该这么大，是不是有视频图片那些
> 
> > > 你这种方案更优，导出HAR不能实时，而且操作繁琐。但是解析HAR文件并不麻烦，就是一json读取几个key而已，花不了多久时间。
> > 
> > 是这样，但是我试着导了一个har，发现文件还是蛮大的，包括APP启动时间我才抓了20秒，他就已经8 MB了，对于我只需要链接的话，属实有点绷不住，我如果要批量抓链接的话，占的内存有点大，总觉得很不舒服，以后如果需求比较复杂，再考虑吧，目前来看，我觉得这方法已经够用了
> 
> 

咱抓的就是视频应用啊，而且主要我懒，我白名单应用很多，但我又不想去关，所以抓包的时候其实是几个应用的流量都会被抓

**Comment by Sharl210** [comment]
目前在作者在我提议的这个功能更新之前，如果有需要的可以在这里说一下，我已经把它做成一个magisk模块了,开机自启,全程30扫描一次保活进程,不传输数据时处于休眠状态，理论耗电量应该不大

**Comment by huaqqdu** [comment]
> 目前在作者更新（如果可能）我提议的这个功能之前，如果和我的场景相似，同样有这方面需要的可以在这里说一下，我传上来，我已经把它做成一个magisk模块了（ksu/ap通用），不再需要termux，直接二进制执行，源代码也附在模块里了,开机自启,全程30秒扫描一次，保活进程,不传输数据时处于休眠状态，理论耗电量应该不大

我也是有这个想法，那种视频或者img和js，zip之类的的文件匹配到是那个网址的统统走本地，这样就无需下载，实现方式要么自己编译一下ProxyPin的源码要么就只能用xposedhook获取到网址再替换掉了

**Comment by Sharl210** [comment]
> > 目前在作者更新（如果可能）我提议的这个功能之前，如果和我的场景相似，同样有这方面需要的可以在这里说一下，我传上来，我已经把它做成一个magisk模块了（ksu/ap通用），不再需要termux，直接二进制执行，源代码也附在模块里了,开机自启,全程30秒扫描一次，保活进程,不传输数据时处于休眠状态，理论耗电量应该不大
> 
> 我也是有这个想法，那种视频或者img和js，zip之类的的文件匹配到是那个网址的统统走本地，这样就无需下载，实现方式要么自己编译一下ProxyPin的源码要么就只能用xposedhook获取到网址再替换掉了

flutter应用呢，xposedhook可解决不了，得深入分析不说，还得用frida，成本大于收益了都😭，所以我才来提议的，上面这个能顶替大部分需求甚至可以自定义很多逻辑了，但我还是想这个能做成一体化的功能

**Comment by huaqqdu** [comment]
> > > 目前在作者更新（如果可能）我提议的这个功能之前，如果和我的场景相似，同样有这方面需要的可以在这里说一下，我传上来，我已经把它做成一个magisk模块了（ksu/ap通用），不再需要termux，直接二进制执行，源代码也附在模块里了,开机自启,全程30秒扫描一次，保活进程,不传输数据时处于休眠状态，理论耗电量应该不大
> > 
> > 
> > 我也是有这个想法，那种视频或者img和js，zip之类的的文件匹配到是那个网址的统统走本地，这样就无需下载，实现方式要么自己编译一下ProxyPin的源码要么就只能用xposedhook获取到网址再替换掉了
> 
> flutter应用呢，xposedhook可解决不了，得深入分析不说，还得用frida，成本大于收益了都😭，所以我才来提议的，上面这个能顶替大部分需求甚至可以自定义很多逻辑了，但我还是想这个能做成一体化的功能

没看到你的附件大佬，好像你的方案也是能解决我的问题

**Comment by Sharl210** [comment]
> > > > 目前在作者更新（如果可能）我提议的这个功能之前，如果和我的场景相似，同样有这方面需要的可以在这里说一下，我传上来，我已经把它做成一个magisk模块了（ksu/ap通用），不再需要termux，直接二进制执行，源代码也附在模块里了,开机自启,全程30秒扫描一次，保活进程,不传输数据时处于休眠状态，理论耗电量应该不大
> > > 
> > > 
> > > 我也是有这个想法，那种视频或者img和js，zip之类的的文件匹配到是那个网址的统统走本地，这样就无需下载，实现方式要么自己编译一下ProxyPin的源码要么就只能用xposedhook获取到网址再替换掉了
> > 
> > flutter应用呢，xposedhook可解决不了，得深入分析不说，还得用frida，成本大于收益了都😭，所以我才来提议的，上面这个能顶替大部分需求甚至可以自定义很多逻辑了，但我还是想这个能做成一体化的功能
> 
> 没看到你的附件大佬，好像你的方案也是能解决我的问题

之前也没人提过类似需求，以为大家需求并不强烈，我也就懒得再发上来了，https://pan.huang1111.cn/s/dk1jOHV，
SHA256:dd1016848c0ce8c29ebe14102bbeeed105c35f33587e27cf37f61f2b47357cd8

**Comment by huaqqdu** [comment]
> > > > > 目前在作者更新（如果可能）我提议的这个功能之前，如果和我的场景相似，同样有这方面需要的可以在这里说一下，我传上来，我已经把它做成一个magisk模块了（ksu/ap通用），不再需要termux，直接二进制执行，源代码也附在模块里了,开机自启,全程30秒扫描一次，保活进程,不传输数据时处于休眠状态，理论耗电量应该不大
> > > > 
> > > > 
> > > > 我也是有这个想法，那种视频或者img和js，zip之类的的文件匹配到是那个网址的统统走本地，这样就无需下载，实现方式要么自己编译一下ProxyPin的源码要么就只能用xposedhook获取到网址再替换掉了
> > > 
> > > 
> > > flutter应用呢，xposedhook可解决不了，得深入分析不说，还得用frida，成本大于收益了都😭，所以我才来提议的，上面这个能顶替大部分需求甚至可以自定义很多逻辑了，但我还是想这个能做成一体化的功能
> > 
> > 
> > 没看到你的附件大佬，好像你的方案也是能解决我的问题
> 
> 之前也没人提过类似需求，以为大家需求并不强烈，我也就懒得再发上来了，https://pan.huang1111.cn/s/dk1jOHV
> 
> SHA256:dd1016848c0ce8c29ebe14102bbeeed105c35f33587e27cf37f61f2b47357cd8

感谢大佬的栽树(≖‿≖)✧

**Comment by Sharl210** [comment]
> > > > > > 目前在作者更新（如果可能）我提议的这个功能之前，如果和我的场景相似，同样有这方面需要的可以在这里说一下，我传上来，我已经把它做成一个magisk模块了（ksu/ap通用），不再需要termux，直接二进制执行，源代码也附在模块里了,开机自启,全程30秒扫描一次，保活进程,不传输数据时处于休眠状态，理论耗电量应该不大
> > > > > 
> > > > > 
> > > > > 我也是有这个想法，那种视频或者img和js，zip之类的的文件匹配到是那个网址的统统走本地，这样就无需下载，实现方式要么自己编译一下ProxyPin的源码要么就只能用xposedhook获取到网址再替换掉了
> > > > 
> > > > 
> > > > flutter应用呢，xposedhook可解决不了，得深入分析不说，还得用frida，成本大于收益了都😭，所以我才来提议的，上面这个能顶替大部分需求甚至可以自定义很多逻辑了，但我还是想这个能做成一体化的功能
> > > 
> > > 
> > > 没看到你的附件大佬，好像你的方案也是能解决我的问题
> > 
> > 之前也没人提过类似需求，以为大家需求并不强烈，我也就懒得再发上来了，https://pan.huang1111.cn/s/dk1jOHV
> > 
> > SHA256:dd1016848c0ce8c29ebe14102bbeeed105c35f33587e27cf37f61f2b47357cd8
> 
> 感谢大佬的栽树(≖‿≖)✧

栽树谈不上，我又不干开发，不熟悉c++，原来的是python写的，我提供思路，ai来实现转成c直接编译成二进制方便做成模块，就不用再用termux了那样太繁琐了

**Comment by Sharl210** [comment]
> 
> 感谢大佬的栽树(≖‿≖)✧

端口8000
接收到的文件将保存在/storage/emulated/0/ Url数据传递(注：开头有空格)
可接受POST/GET 
格式样式"data=xxx&name=xxx",为避免出错
最好脚本转发时将data字段的数据url编码encodeURIComponent()

**Comment by huaqqdu** [comment]
> > 感谢大佬的栽树(≖‿≖)✧
> 
> 端口8000 接收到的文件将保存在/storage/emulated/0/ Url数据传递(注：开头有空格) 可接受POST/GET 格式样式"data=xxx&name=xxx",为避免出错 最好脚本转发时将data字段的数据url编码encodeURIComponent()

我看了一下代码，大概流程就是转到本地服务器，然后解析转发过来的请求，问题是请求重新，重定向到本地服务器，是不带原网址的，怎么能根据网址去匹配呢

**Comment by Sharl210** [comment]
> > > 感谢大佬的栽树(≖‿≖)✧
> > 
> > 端口8000 接收到的文件将保存在/storage/emulated/0/ Url数据传递(注：开头有空格) 可接受POST/GET 格式样式"data=xxx&name=xxx",为避免出错 最好脚本转发时将data字段的数据url编码encodeURIComponent()
> 
> 我看了一下代码，大概流程就是转到本地服务器，然后解析转发过来的请求，问题是请求重新，重定向到本地服务器，是不带原网址的，怎么能根据网址去匹配呢

proxypin不是有脚本功能吗，他有网址匹配啊，通配符不够用那就在脚本里再过滤一次后转发呗，我的本意是在脚本功能初次处理完以后，把最终结果转到本地存，这个模块主要用来''存''，因为毕竟是编译成了二进制，它可拓展性不强，脚本功能里你可以执行更多的自定义操作

**Comment by huaqqdu** [comment]
> > > > 感谢大佬的栽树(≖‿≖)✧
> > > 
> > > 
> > > 端口8000 接收到的文件将保存在/storage/emulated/0/ Url数据传递(注：开头有空格) 可接受POST/GET 格式样式"data=xxx&name=xxx",为避免出错 最好脚本转发时将data字段的数据url编码encodeURIComponent()
> > 
> > 
> > 我看了一下代码，大概流程就是转到本地服务器，然后解析转发过来的请求，问题是请求重新，重定向到本地服务器，是不带原网址的，怎么能根据网址去匹配呢
> 
> proxypin不是有脚本功能吗，他有网址匹配啊，通配符不够用那就在脚本里再过滤一次后转发呗，我的本意是在脚本功能初次处理完以后，把最终结果转到本地存，这个模块主要用来''存''，因为毕竟是编译成了二进制，它可拓展性不强，你要在这里加新功能或者加新的逻辑的话，得重新从源码再编译过来，而脚本里只需要改一下脚本就行了呀，脚本功能里你可以执行更多的自定义操作，而且我这里解决的只是把视频解析出来的链接保存到本地，然后我用其他下载器批量下载，不是直接能够把文件解析到本地，所以说是暂时的替代方案，还是要等大佬更新

脚本那里我尝试修改url（实现重定向），失败了，所以是不能获取原网址+请求到本地（http://127.0.0.1/url=https://baidu.com），还是有空研究一下怎么编译源代码吧，直接从代码搞应该好点

**Comment by Sharl210** [comment]
> > > > > 感谢大佬的栽树(≖‿≖)✧
> > > > 
> > > > 
> > > > 端口8000 接收到的文件将保存在/storage/emulated/0/ Url数据传递(注：开头有空格) 可接受POST/GET 格式样式"data=xxx&name=xxx",为避免出错 最好脚本转发时将data字段的数据url编码encodeURIComponent()
> > > 
> > > 
> > > 我看了一下代码，大概流程就是转到本地服务器，然后解析转发过来的请求，问题是请求重新，重定向到本地服务器，是不带原网址的，怎么能根据网址去匹配呢
> > 
> > proxypin不是有脚本功能吗，他有网址匹配啊，通配符不够用那就在脚本里再过滤一次后转发呗，我的本意是在脚本功能初次处理完以后，把最终结果转到本地存，这个模块主要用来''存''，因为毕竟是编译成了二进制，它可拓展性不强，你要在这里加新功能或者加新的逻辑的话，得重新从源码再编译过来，而脚本里只需要改一下脚本就行了呀，脚本功能里你可以执行更多的自定义操作，而且我这里解决的只是把视频解析出来的链接保存到本地，然后我用其他下载器批量下载，不是直接能够把文件解析到本地，所以说是暂时的替代方案，还是要等大佬更新
> 
> 脚本那里我尝试修改url（实现重定向），失败了，所以是不能获取原网址+请求到本地（http://127.0.0.1/url=https://baidu.com），还是有空研究一下怎么编译源代码吧，直接从代码搞应该好点

首先你得看我上面说的数据请求格式，其次，我这个相当于日志的那种作用，其次你这个请求，不是我这个模块的本意，最好的办法是直接用请求重写功能，利用重定向定向到本地的某个端口，然后你在本地写对这个网址响应的处理逻辑然后启用端口来接受Proxypin的转发数据，或者你硬是要用，你就把你想要重定向的网址的响应在脚本功能里先把它封装为一个数据包，比如用base64加密（总之只要不影响外部传输就行）到本地再自己解析这个数据包，但是这玩意怎么说呢？也就是把大部分任务交给了这个二进制来完成，你得从源码下手，但是我觉得c的网络请求都是一言难尽，python/js就舒服多，所以如果你的需求是完整重定向的话，建议还是自己实现，写个完整的本地http服务器来接收，我这个是针对我的需求写的阉割版，代码并不复杂，而且刚好完美能契合我的需求。

**Comment by Sharl210** [comment]
> > > > > 感谢大佬的栽树(≖‿≖)✧
> > > > 
> > > > 
> > > > 端口8000 接收到的文件将保存在/storage/emulated/0/ Url数据传递(注：开头有空格) 可接受POST/GET 格式样式"data=xxx&name=xxx",为避免出错 最好脚本转发时将data字段的数据url编码encodeURIComponent()
> > > 
> > > 
> > > 我看了一下代码，大概流程就是转到本地服务器，然后解析转发过来的请求，问题是请求重新，重定向到本地服务器，是不带原网址的，怎么能根据网址去匹配呢
> > 
> > proxypin不是有脚本功能吗，他有网址匹配啊，通配符不够用那就在脚本里再过滤一次后转发呗，我的本意是在脚本功能初次处理完以后，把最终结果转到本地存，这个模块主要用来''存''，因为毕竟是编译成了二进制，它可拓展性不强，你要在这里加新功能或者加新的逻辑的话，得重新从源码再编译过来，而脚本里只需要改一下脚本就行了呀，脚本功能里你可以执行更多的自定义操作，而且我这里解决的只是把视频解析出来的链接保存到本地，然后我用其他下载器批量下载，不是直接能够把文件解析到本地，所以说是暂时的替代方案，还是要等大佬更新
> 
> 脚本那里我尝试修改url（实现重定向），失败了，所以是不能获取原网址+请求到本地（http://127.0.0.1/url=https://baidu.com），还是有空研究一下怎么编译源代码吧，直接从代码搞应该好点

还有请忽略我这个模块的取名，我也不知道怎么取，所以随便取的，我本来只是proxypin抓包时过滤对应的视频网址，然后用这个模块存到本地,所以叫做urldata,就是直译''网址链接''数据

**Comment by wanghongenpin** [comment]
我可以提供read, write 等简单操作文件API

**Comment by Sharl210** [comment]
> 我可以提供read, write 等简单操作文件API

好耶，这个可以，我就是要这个（即答）

**Comment by wanghongenpin** [comment]
V1.1.5版本已经处理
https://github.com/wanghongenpin/network_proxy_flutter/releases/tag/V1.1.5
文档：https://github.com/wanghongenpin/network_proxy_flutter/wiki/%E8%AF%B7%E6%B1%82%E9%87%8D%E5%86%99

**Comment by Sharl210** [comment]
> V1.1.5版本已经处理 https://github.com/wanghongenpin/network_proxy_flutter/releases/tag/V1.1.5 文档：https://github.com/wanghongenpin/network_proxy_flutter/wiki/%E8%AF%B7%E6%B1%82%E9%87%8D%E5%86%99

收到👍

**Comment by Sharl210** [comment]
> V1.1.5版本已经处理
> https://github.com/wanghongenpin/network_proxy_flutter/releases/tag/V1.1.5
> 文档：https://github.com/wanghongenpin/network_proxy_flutter/wiki/%E8%AF%B7%E6%B1%82%E9%87%8D%E5%86%99

老大,这个是不是还有一些文件权限问题？就是我是安卓15，然后我测了一下，我好像内部储存任何一个目录都不行，但这个比较玄，有时候Download他又可以写入，然后现在我都是直接写死软件本身的私有目录/data/user/0/com.network.proxy/files和/storage/emulated/0/Android/data/com.network.proxy下，他才会不出问题

**Comment by wanghongenpin** [comment]
安全文件权限机制，其他目录未授权不让访问，我觉得这是正常的

> 老大,这个是不是还有一些文件权限问题？就是我是安卓15，然后我测了一下，我好像内部储存任何一个目录都不行，但这个比较玄，有时候Download他又可以写入，然后现在我都是直接写死软件本身的私有目录/data/user/0/com.network.proxy/files和/storage/emulated/0/Android/data/com.network.proxy下，他才会不出问题

**Comment by Sharl210** [comment]
> 安全文件权限机制，其他目录未授权不让访问，我觉得这是正常的
> 
> > 老大,这个是不是还有一些文件权限问题？就是我是安卓15，然后我测了一下，我好像内部储存任何一个目录都不行，但这个比较玄，有时候Download他又可以写入，然后现在我都是直接写死软件本身的私有目录/data/user/0/com.network.proxy/files和/storage/emulated/0/Android/data/com.network.proxy下，他才会不出问题
> 
> 

那我怎么主动给他授权啊😂
