### ISSUE TITLE
建议将请求重写添加/修改窗口改为全屏大窗口

### ISSUE THREAD

**Issue by mdikjse** [wanghongenpin/proxypin#319]
**您的功能请求是否与问题有关？请描述.有关
对问题所在的清晰简洁的描述[目前添加请求重写时以及修改时是以弹窗形式修改，如果修改存在换行的情况会导致换行符丢失]

**描述您想要的解决方案**
对你想要发生的事情进行清晰简洁的描述.
希望在添加/修改请求重写时像编辑脚本时一样单开一个窗口，这样会大一点，对多行文本进行请求重写时会比较友好方便。
**附加上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。
![Screenshot_20240924_183855_com network proxy](https://github.com/user-attachments/assets/f459963d-bcfc-40df-999c-d05cdd6cdfb5)

**Comment by wanghongenpin** [comment]
这样怕页面太深了

**Comment by mdikjse** [comment]
> 这样怕页面太深了

确实有点深，那把输入框改为多行文本呢，会不会出现行数太多超出屏幕。。。确实目前的方案修改多行会出现问题

**Comment by wanghongenpin** [comment]
下个版本优化

**Comment by wanghongenpin** [comment]
先调整为3行是否能满足

![image](https://github.com/user-attachments/assets/0d28b458-f72d-45da-bebb-6e89bf242c6b)

**Comment by mdikjse** [comment]
实在不好调整的话要不就设置输入框的高度超过3行或5行显示滚动条，这样可以不？3行滚动条的话不是很好操作，建议最好加个滚动条，这样多几行也可以用

**Comment by wanghongenpin** [comment]
V1.1.5版本已经处理
https://github.com/wanghongenpin/network_proxy_flutter/releases/tag/V1.1.5

**Comment by mdikjse** [comment]
> V1.1.5版本已经处理 https://github.com/wanghongenpin/network_proxy_flutter/releases/tag/V1.1.5

感谢。。。
