### ISSUE TITLE
[iOS]抓包https的请求出现 ssl handshake failed

### ISSUE THREAD

**Issue by GhostClock** [wanghongenpin/proxypin#323]
**描述错误(Describe the bug)**
如题。
确定安装了证书并且已经在关于里面信任过了的，还是出现了
`-2 ssl handshake failed，请检查证书安装是否正确`

**To Reproduce**
iOS版本：16.7.1
软件版本：1.1.3

**屏幕截图(Screenshots)*
![IMG_6043](https://github.com/user-attachments/assets/a95fc0a6-4b54-42bf-98c5-55e3e6740569)

**Comment by wanghongenpin** [comment]
抓什么应用，其他抓包阮家可以抓吗

**Comment by sseen** [comment]
我也试了下，遇到了同样的问题。但是试了新版小黄鸟reqable，应该也是用flutter做的，却可以正常抓取。

**Comment by wanghongenpin** [comment]
抓什么应用？是全部都是抓包失败还是部分，全部抓包失败大概率证书安装问题

**Comment by sseen** [comment]
重置了下，默认根证书，现在twitter可以了。但是instagram还是不行

**Comment by GhostClock** [comment]
> 抓什么应用，其他抓包阮家可以抓吗

丰云行，微信，都抓不到，但是很奇怪，只有部分接口报这个问题，应该是这些接口是关键接口，自建证书不行吗？

**Comment by wanghongenpin** [comment]
发其他抓包应用和本应用抓包截图,以及哪个页面

> 丰云行，微信，都抓不到，但是很奇怪，只有部分接口报这个问题，应该是这些接口是关键接口，自建证书不行吗？

**Comment by wanghongenpin** [comment]
如果其他应用可以抓到, 本抓不了欢迎提供截图, 以及复现步骤, 如果都抓不了, 可能对证书做了校验

**Comment by wanghongenpin** [comment]
> 我也是，ios 彩云天气更新了最新版本就这样了

这个软件做了证书校验，需要你自己去研究

**Comment by wanghongenpin** [comment]
> 我也试了下，遇到了同样的问题。但是试了新版小黄鸟reqable，应该也是用flutter做的，却可以正常抓取。

什么应用，有截图吗

**Comment by JJYi1** [comment]
我也遇到了这个问题。东航app
最离谱的是一开始还可以抓，过了30分钟之后突然不行了

**Comment by wanghongenpin** [comment]
> 我也遇到了这个问题。东航app 最离谱的是一开始还可以抓，过了30分钟之后突然不行了

尝试使用其他抓包软件可以不，如果不可以，那就是做了证书校验

**Comment by wanghongenpin** [comment]
尝试使用其他抓包软件可以不，如果可以欢迎来反馈

**Comment by tycn888** [comment]
IOS 17.7 
头条、红果免费视频 无法抓包，反馈：ssl handshake failed
app要求证书验证了，小白不会弄了
