### ISSUE TITLE
[Windows、Mac、Android]创建两个相同URL的重写规则，只生效一个

### ISSUE THREAD

**Issue by czpandy** [wanghongenpin/proxypin#331]
**描述错误(Describe the bug)**
重写有个BUG
创建两个相同URL的重写规则，只生效一个

**To Reproduce**
重现行为的步骤: 如具体应用抓包失败，请说明软件名称以及具体操作页面
创建两个相同URL的重写规则：
规则1，www.baidu.com，修改请求，修改body，1xxx
规则2，www.baidu.com，修改请求，修改body，2xxx
两个都选择，只会生效一个，期望是两个都生效

**屏幕截图(Screenshots)*

**Comment by wanghongenpin** [comment]
为什么要建两个, 重写不重复了吗?  一个重写规则 在详情页可以默认填充

**Comment by czpandy** [comment]
> 为什么要建两个, 重写不重复了吗? 一个重写规则 在详情页可以默认填充

一个规则没问题，就是去选择比较麻烦，要多点进去2层。

**Comment by wanghongenpin** [comment]
选择哪里麻烦，有截图吗
> 
> 一个规则没问题，就是去选择比较麻烦，要多点进去2层。

**Comment by wanghongenpin** [comment]
V1.1.5版本已经处理
https://github.com/wanghongenpin/network_proxy_flutter/releases/tag/V1.1.5
