### ISSUE TITLE
[IOS]请求header修改对于个别APP不生效

### ISSUE THREAD

**Issue by WaveBird** [wanghongenpin/proxypin#336]
**描述错误(Describe the bug)**

首先十分感谢大佬的开源和开发，今天使用的时候，发现https的请求头无论是删除，修改，还是新增都没有生效，尝试重启软件，重启手机都不可以，请求参数修改和响应修改是可以生效的，只有请求header没有生效。

对于safari浏览器产生的请求，请求头的修改（增加）能够生效。

软件版本: v1.1.3

**To Reproduce**
重现行为的步骤: 如具体应用抓包失败，请说明软件名称以及具体操作页面
1. 下载now冥想app
2. 任意接口 新增请求头或者删除请求头
3. 打开app触发请求
4. 请求详情中请求头没有变化，配置的请求头修改没有生效

**屏幕截图(Screenshots)*
![image](https://github.com/user-attachments/assets/7991aa50-e7dc-4b02-a489-5ed6e4798bb9)
![image](https://github.com/user-attachments/assets/fd273269-294f-4235-b8ea-95e90c3347fc)
![image](https://github.com/user-attachments/assets/75457f02-fd10-476d-a33b-f65557be0bd6)

**Comment by WaveBird** [comment]
是指把请求转成curl然后发到评论里吗

**Comment by wanghongenpin** [comment]
> 是指把请求转成curl然后发到评论里吗

对，可以先使用最新版本试下，看是否还有问题
