### ISSUE TITLE
iOS重新生成的根证书用不了

### ISSUE THREAD

**Issue by 450316** [wanghongenpin/proxypin#338]
![image](https://github.com/user-attachments/assets/16b49373-f7f3-4fd8-925e-809c12ca23bb)
![image](https://github.com/user-attachments/assets/9ed60a4e-9ec5-4fec-9096-7e33c1b8bc4c)

**Comment by wanghongenpin** [comment]
先用默认的根证书

**Comment by wanghongenpin** [comment]
V1.1.5版本已经处理
https://github.com/wanghongenpin/network_proxy_flutter/releases/tag/V1.1.5
