### ISSUE TITLE
[Windows]LINK : fatal error LNK1104:

### ISSUE THREAD

**Issue by wangtl** [wanghongenpin/proxypin#347]
**描述错误(Describe the bug)**
我在idea里本地运行windows环境，在编译的时候报错：LINK : fatal error LNK1104: �޷����ļ���atls.lib�� [D:\cockler\network_proxy_flutter\build\windows\x64\plugins\win32audio\win32audio_plugin.vcxproj]

**屏幕截图(Screenshots)*
![image](https://github.com/user-attachments/assets/bb2aa588-8361-43ca-aad5-c84da504ad2b)

**Comment by wanghongenpin** [comment]
使用flutter最新版本

**Comment by wangtl** [comment]
我当前的flutter的版本已经是3.24.3了

**Comment by wanghongenpin** [comment]
网上搜索吧，我试了几个电脑都可以编译通过

**Comment by wanghongenpin** [comment]
flutter clean
flutter pub get

不行网上搜索下,大概率和你环境有关系

**Comment by wangtl** [comment]
找到原因了，我本地的windows环境缺少ATL的库，用visual studio装一下就行了。感谢你的解答和帮助！
