### ISSUE TITLE
[Windows] 设置项重复

### ISSUE THREAD

**Issue by geekyouth** [wanghongenpin/proxypin#348]
![image](https://github.com/user-attachments/assets/e53fe4f3-7588-4ab7-ba4e-32372ce95844)

**Comment by wanghongenpin** [comment]
已经处理，下个版本发布

**Comment by wanghongenpin** [comment]
V1.1.5版本已经处理
https://github.com/wanghongenpin/network_proxy_flutter/releases/tag/V1.1.5
