### ISSUE TITLE
proxypin和clash等折跃工具出现冲突（两者都会占用代理端口，导致proxypin开启的时候无法访问外网）

### ISSUE THREAD

**Issue by msh01** [wanghongenpin/proxypin#351]
![image](https://github.com/user-attachments/assets/b0e9bfb3-bbd2-425f-abfc-ba35e1a0fea3)

 如图，两者都会把Windows上面的代理服务器改为自己的端口

**Comment by wanghongenpin** [comment]
外部代理
![image](https://github.com/user-attachments/assets/7ef36770-719a-42b7-b9b7-ba2c9085ccc4)

**Comment by wanghongenpin** [comment]
vpn转发proxypin or proxypin外部代理转发vpn

**Comment by msh01** [comment]
感谢
