### ISSUE TITLE
本项目非常好，UI上感觉可以参考Reqable

### ISSUE THREAD

**Issue by abel533** [wanghongenpin/proxypin#353]
目前一直在用Reqable，用的比较简单，付费功能不是必须的，想过有没有类似开源实现，今天才看到本项目。

本项目核心功能和Reqable差不多，主要是UI和易用性的不足。

感觉可以参考Reqable的UI设计，我本地有 Flutter 开发环境，找时间看看能不能学会。

![image](https://github.com/user-attachments/assets/0f6f3896-b32d-4e9e-8070-b1ac04ad9e8f)

**Comment by MegatronKing** [comment]
@wanghongenpin  偶然看到这个Issue提到reqable，我就借楼简单说说。

Reqable的UI/UX并不算好，因为我也不是专业产品和设计师，交互和设计我自己也不满意，一直在改，如果要参考Reqable并不一定是好的选择，而且产品保持差异化很重要。

然后，我发现这个项目很多用语和交互设计和Reqable几乎一样，比如重写，工具箱，不知道是有意还是无意，这个其实真没必要。像很多用语我是为了特地避开和Proxyman、Charles的一模一样，所以没有用Map Local，Map Remote这些词，但事实上这并不是好的选择，当然交互也是一样，是我想多了。

Proxypin是个优秀的开源项目，希望作者再接再厉，同时有更多自己的思考。
