### ISSUE TITLE
设备端IP层协议抓包&TCP包支持

### ISSUE THREAD

**Issue by SoY0ung** [wanghongenpin/proxypin#354]
谢谢您的开源。

了解到App Store上的 [Hodor](https://apps.apple.com/cn/app/id1608857736) 是直接在设备端IP层来抓包的，也可以抓取Flutter App的流量。未来ios版本是否会支持设备端IP层抓包呢。
可以添加对TCP数据包的预览和改写吗，抓取游戏数据包时可能会用到。

**Comment by jtyang** [comment]
@wanghongenpin 大佬，请教下现在安卓端是还无法抓取tcp长连接的包吗？

**Comment by woeoio** [comment]
同问

> [@wanghongenpin](https://github.com/wanghongenpin) 大佬，请教下现在安卓端是还无法抓取tcp长连接的包吗？

**Comment by jtyang** [comment]
您好，邮件已经收到，我会尽快回复您！祝您开心...
