### ISSUE TITLE
[Android]10发现一个字符串处理bug及关于按钮事件

### ISSUE THREAD

**Issue by mdikjse** [wanghongenpin/proxypin#356]
**描述错误(Describe the bug)**

**To Reproduce**
重现行为的步骤: 如具体应用抓包失败，请说明软件名称以及具体操作页面

**屏幕截图(Screenshots)*
1、1.15版本点击关于后无反应，可能是点击事件未设置跳转
2、设置请求屏蔽后请求仍然可以正常被请求，查看发现字符之间多出了几个非打印字符

Uploading SVID_20241030_202403_1.mp4…

**Comment by mdikjse** [comment]
Uploading SVID_20241030_202403_1.mp4…

**Comment by wanghongenpin** [comment]
下个版本处理
