### ISSUE TITLE
证书有效期

### ISSUE THREAD

**Issue by beichen2023** [wanghongenpin/proxypin#358]
明明信任了系统的根证书,但是仍然无法正常抓包,根证书列表中已经开启了
是不是因为最近证书都是不能超过6个月?我看系统生成的证书10年的有效期

能不能自定义生成的证书的有效期?

**Comment by wanghongenpin** [comment]
跟证书有效时间没关系

**Comment by Left-Hai** [comment]
我在最新版上也碰到了这个问题，在根证书里将ProxyPin的证书状态设置为不可用后解决了
