### ISSUE TITLE
[iOS]部分请求的Request URL中的域名被重定向为ip

### ISSUE THREAD

**Issue by InfinityNing** [wanghongenpin/proxypin#361]
首先不确定这是不是一个非预期的错误，还是我这里配置有什么问题，烦请赐教。

**描述错误(Describe the bug)**
    iOS端开启抓包后，可话app中大多数图片（也有可能是全部图片）无法显示。
    这些都是发给cdn的HTTPS请求，但即使不开启HTTPS代理，图片也无法显示。
    
**To Reproduce**
    app：可话
    具体出问题的界面：所有需要联网加载的页面，比如个人信息页面的头像
    HTTPS 代理：已启用
    证书：已安装并信任
    复现方式：
        1、proxypin 点击开始
        2、进入可话 app，头像、动态中的图片均不显示
        3、查看 proxypin 域名列表，发现涉及到 cdn 的请求都返回 403/404
        4、查看这些请求的「抓包详情」，发现 header 的 host 是域名，但 Requst URL 是 ip
        5、在「请求编辑」页面手动把 Requst URL 的 ip 改成域名，发送请求能正常收到响应

**屏幕截图(Screenshots)**
    如果有需要可以提供

**Comment by wanghongenpin** [comment]
有截图吗，以及curl请求

**Comment by InfinityNing** [comment]
> 有截图吗，以及curl请求

如下是失败的curl请求，以及截图
我在如果把ip换成host头的域名就可以访问
比较奇怪的是，使用别的工具貌似没有遇到这个问题，比如stream，就是正常请求的域名
curl -X GET 'http://111.32.160.6/images/251fccf602d6a8a5eda1d09753c3f9a6.jpeg' \
  -H 'Host: cdn-back.tideswing.fun' \
  -H 'Proxy-Connection: keep-alive' \
  -H 'Accept: image/*,*/*;q=0.8' \
  -H 'User-Agent: ke hua/1.12.5 (iPhone; iOS 18.1; Scale/3.00)' \
  -H 'Accept-Language: zh-CN,zh-Hans;q=0.9' \
  -H 'Accept-Encoding: gzip, deflate, br' \
  -H 'Connection: keep-alive'  \
   --compressed ProxyPin全平台抓包软件

![image](https://github.com/user-attachments/assets/5b043112-dda1-4625-aff7-999a3948dc74)
![image](https://github.com/user-attachments/assets/cb65fe79-2675-4138-b15f-6d8c0ae2bf21)
![image](https://github.com/user-attachments/assets/3ee806d4-ba08-4a0b-a76f-d800e618dc4a)

**Comment by wanghongenpin** [comment]
下版本发布
