### ISSUE TITLE
脚本里支持post请求么

### ISSUE THREAD

**Issue by youngzhang26** [wanghongenpin/proxypin#363]
范例里的get请求，我试验了可以。
然后我想在onResponse里执行post操作，发现就卡住了 也没有日志看到是哪里出错

**Comment by wanghongenpin** [comment]
可以， 多试试

![QQ_1731254413581](https://github.com/user-attachments/assets/25a77861-3b3b-47b3-bf3f-fb924d1ed81f)

**Comment by youngzhang26** [comment]
谢谢 确实可以

**Comment by youngzhang26** [comment]
谢谢 确实可以
