### ISSUE TITLE
连接wifi，提示验证。获捕不了这个请求。

### ISSUE THREAD

**Issue by 456vv** [wanghongenpin/proxypin#365]

**Comment by wanghongenpin** [comment]
请提供详细信息

**Comment by 456vv** [comment]
免费wifi，连接后，需要输入手机号码和验证码，才能正常上网。我想知道它的工作方式。开启proxypin，进入vpn模式。没有获捕到它这个网络请求。

**Comment by wanghongenpin** [comment]
尝试使用其他抓包软件看能抓到不，抓不到说明做了特殊处理

**Comment by 456vv** [comment]
这个是在系统上走http。难道 vpn 不能全局，或 系统上的请求是绕过 vpn ?

**Comment by wanghongenpin** [comment]
抓包原理介绍： https://github.com/wanghongenpin/proxypin/wiki/%E6%8A%93%E5%8C%85%E5%8E%9F%E7%90%86%E4%BB%8B%E7%BB%8D

怎么抓需要你自己研究，如果是软件bug欢迎反馈
