### ISSUE TITLE
某 红书 发现页，脚本功能异常

### ISSUE THREAD

**Issue by iPsxp** [wanghongenpin/proxypin#367]
**描述错误(Describe the bug)**
[Android]开启脚本的时候 发现页请求失败406，不开启脚本就没事 正常，且设置请求重写都可以正常更改响应体，通过脚本即使是什么都不改都会异常....是不是和重写的逻辑不一样啊。。。辛苦作者有空看下，谢谢！

**To Reproduce**
重现行为的步骤: 
打开app首页刷新home feed接口，开启脚本即可复现，(其他接口可以正常开启)。

**屏幕截图(Screenshots)*
![image](https://github.com/user-attachments/assets/6b02e3ee-940c-4f06-8546-9ee46dafe3f9)

**Comment by dreams-iP** [comment]
已经可以了 谢谢您

**Comment by dreams-iP** [comment]
> 1.1.6版本已经处理
> 
> https://github.com/wanghongenpin/proxypin/releases/tag/v1.1.6

可以了谢谢您！
