### ISSUE TITLE
[Android] 单独发布一个arm64版本的apk

### ISSUE THREAD

**Issue by 1q23lyc45** [wanghongenpin/proxypin#381]
**您的功能请求是否与问题有关？请描述.**
Proxypin的apk，包含含了全部架构的so库。不过，现在绝大部分手机都是arm64架构了，还是一个apk所有so，可能有点浪费空间了。

**描述您想要的解决方案**
像1.0.9那样，单独打包一个arm64版本apk发布，原来的通用架构版本apk保持不变。
谢谢！

**Comment by wanghongenpin** [comment]
1.1.6版本已增加arm64

**Comment by 1q23lyc45** [comment]
> 1.1.6版本已增加arm64

谢谢！
