### ISSUE TITLE
[Android]证书安装成功后，无法抓flutter应用包请求数据

### ISSUE THREAD

**Issue by snila** [wanghongenpin/proxypin#398]
![1C5A721D849AC3C1C1041657DAF0AC08](https://github.com/user-attachments/assets/106c1809-1856-42bb-a8a4-d26a0a545f71)
![AA1F828D886B5D3A98924464E6CB9001](https://github.com/user-attachments/assets/9b0cb6d8-f8ba-4e46-a2c6-367b9eeccc73)
![38065D9EEC3A565E617B0217A8A8BDE4](https://github.com/user-attachments/assets/30a08f2f-af0a-4188-aa39-05b2df58080f)
![013161556F6EE98F7ED85EA203D6A76C](https://github.com/user-attachments/assets/550c6098-3252-4bf7-9206-f6be53ab845e)

status code ：-2 SSL handshake failed,请检查证书安装是否正确

**Comment by wanghongenpin** [comment]
需要root，安装到系统证书，详细可以搜索安卓7版本以上抓包问题

**Comment by snila** [comment]
手机必须要root吗？有不需要root的方法吗

**Comment by wanghongenpin** [comment]
看软件是否信任用户证书，网上搜索有大量的文章

**Comment by guanhui07** [comment]
> 需要系统证书，非软件bug

请教下  iphone   iOS17.7 版本 有办法抓包到 flutter 写的app 请求的api吗

**Comment by snila** [comment]
> 需要root，安装到系统证书，详细可以搜索安卓7版本以上抓包问题

![484deae15dd792ab0d321919410ba83a](https://github.com/user-attachments/assets/c867a699-dcf9-40f6-a9cc-3eed5bdf45c0)
![5174811609b5a3ec580c77eebb9918e4](https://github.com/user-attachments/assets/4fc7a0ce-b27f-44a5-83d5-736b70c4d749)
![68237006f2b262150ac0287c303b35c0](https://github.com/user-attachments/assets/3655008f-906a-43b5-bbbb-f9641b07cb50)
您好，手机已经root了，且系统证书、用户证书都已安装，还是无法抓到flutter应用包，请问还有什么原因吗
